# Generated by Django 2.0.3 on 2018-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=15)),
                ('Role', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=25)),
                ('Phone', models.CharField(max_length=10)),
                ('EmpId', models.CharField(max_length=10)),
                ('Pin', models.CharField(max_length=6)),
            ],
        ),
    ]
